plugins {
    id 'java'
}

group = 'org.fuxkinghatred'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.16.1'
    testImplementation 'io.qameta.allure:allure-junit5:2.24.0'
    testImplementation 'org.slf4j:slf4j-simple:2.0.9'
}

test {
    useJUnitPlatform()
}
